# Get docker for your system @ https://docs.docker.com/get-docker/
#   Docker for Linux
#   Docker Desktop for Windows / macOS
# 
# Use the following commands to start the cluster
#   Starting:
#     $ docker-compose -f docker-compose.yml up
#   Deleteing all ZooKeeper sanpshots:
#     $ docker-compose -f docker-compose.yml down -v
 
version: '3'

services:
  zookeeper1:
    image: docker.io/bitnami/zookeeper:3.7
    hostname: zoo1.zk.local
    ports:
      - 2181:2181
    volumes:
      - zookeeper1_data:/bitnami
    networks:
      - zookeeper
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zoo1.zk.local:2888:3888

  node00:
    environment:
      - SHARD=0
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 10000:8080
    networks:
      - zookeeper
    cpu_count: 1

#  node01:
#    environment:
#      - SHARD=0
#    build:
#      context: .
#      dockerfile: ./docker/Dockerfile
#    ports:
#      - 10001:8080
#    networks:
#      - zookeeper
#    cpu_count: 1
#
#  node02:
#    environment:
#      - SHARD=0
#    build:
#      context: .
#      dockerfile: ./docker/Dockerfile
#    ports:
#      - 10002:8080
#    networks:
#      - zookeeper
#    cpu_count: 1

  node10:
    environment:
      - SHARD=1
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 10003:8080
    networks:
      - zookeeper
    cpu_count: 1
#
#  node11:
#    environment:
#      - SHARD=1
#    build:
#      context: .
#      dockerfile: ./docker/Dockerfile
#    ports:
#      - 10004:8080
#    networks:
#      - zookeeper
#    cpu_count: 1
#
#  node12:
#    environment:
#      - SHARD=1
#    build:
#      context: .
#      dockerfile: ./docker/Dockerfile
#    ports:
#      - 10005:8080
#    networks:
#      - zookeeper
#    cpu_count: 1

  node20:
    environment:
      - SHARD=2
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 10006:8080
    networks:
      - zookeeper
    cpu_count: 1

#  node21:
#    environment:
#      - SHARD=2
#    build:
#      context: .
#      dockerfile: ./docker/Dockerfile
#    ports:
#      - 10007:8080
#    networks:
#      - zookeeper
#    cpu_count: 1
#
#  node22:
#    environment:
#      - SHARD=2
#    build:
#      context: .
#      dockerfile: ./docker/Dockerfile
#    ports:
#      - 10008:8080
#    networks:
#      - zookeeper
#    cpu_count: 1
#

  zoonavigator:
    image: elkozmon/zoonavigator:1.1.1
    hostname: navigator.zk.local
    ports:
      - 9000:9000
    networks:
      - zookeeper
    environment:
      HTTP_PORT: 9000
      CONNECTION_ZKLOCAL1_NAME: ZooKeeper Server 1
      CONNECTION_ZKLOCAL1_CONN: zoo1.zk.local
      AUTO_CONNECT_CONNECTION_ID: ZKLOCAL1

networks:
  zookeeper:

volumes:
  zookeeper1_data:
    driver: local